[logging]
LOG_LEVEL = DEBUG

[server]
HTTP_PORT = 9999
DEV = false
# internal to check the need to restart Python kernel
CHECK_KERNEL_INTERVAL_SECS = 600
# total number of runs of steps before restarting a Python kernel
RUN_COUNT_TO_RESTART_KERNEL = 1000

[gateway]
GATEWAY_URL = http://127.0.0.1:8888
GATEWAY_WS_URL = ws://localhost:8888


[redis]
REDIS_HOST = 127.0.0.1
REDIS_PORT = 6379
